// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gogo.proto

#include "gogo.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

namespace gogoproto {
}  // namespace gogoproto
void InitDefaults_gogo_2eproto() {
}

constexpr ::google::protobuf::Metadata* file_level_metadata_gogo_2eproto = nullptr;
constexpr ::google::protobuf::EnumDescriptor const** file_level_enum_descriptors_gogo_2eproto = nullptr;
constexpr ::google::protobuf::ServiceDescriptor const** file_level_service_descriptors_gogo_2eproto = nullptr;
const ::google::protobuf::uint32 TableStruct_gogo_2eproto::offsets[1] = {};
static constexpr ::google::protobuf::internal::MigrationSchema* schemas = nullptr;
static constexpr ::google::protobuf::Message* const* file_default_instances = nullptr;

::google::protobuf::internal::AssignDescriptorsTable assign_descriptors_table_gogo_2eproto = {
  {}, AddDescriptors_gogo_2eproto, "gogo.proto", schemas,
  file_default_instances, TableStruct_gogo_2eproto::offsets,
  file_level_metadata_gogo_2eproto, 0, file_level_enum_descriptors_gogo_2eproto, file_level_service_descriptors_gogo_2eproto,
};

const char descriptor_table_protodef_gogo_2eproto[] =
  "\n\ngogo.proto\022\tgogoproto\032\020descriptor.prot"
  "o:;\n\023goproto_enum_prefix\022\034.google.protob"
  "uf.EnumOptions\030\261\344\003 \001(\010:=\n\025goproto_enum_s"
  "tringer\022\034.google.protobuf.EnumOptions\030\305\344"
  "\003 \001(\010:5\n\renum_stringer\022\034.google.protobuf"
  ".EnumOptions\030\306\344\003 \001(\010:7\n\017enum_customname\022"
  "\034.google.protobuf.EnumOptions\030\307\344\003 \001(\t:0\n"
  "\010enumdecl\022\034.google.protobuf.EnumOptions\030"
  "\310\344\003 \001(\010:A\n\024enumvalue_customname\022!.google"
  ".protobuf.EnumValueOptions\030\321\203\004 \001(\t:;\n\023go"
  "proto_getters_all\022\034.google.protobuf.File"
  "Options\030\231\354\003 \001(\010:\?\n\027goproto_enum_prefix_a"
  "ll\022\034.google.protobuf.FileOptions\030\232\354\003 \001(\010"
  ":<\n\024goproto_stringer_all\022\034.google.protob"
  "uf.FileOptions\030\233\354\003 \001(\010:9\n\021verbose_equal_"
  "all\022\034.google.protobuf.FileOptions\030\234\354\003 \001("
  "\010:0\n\010face_all\022\034.google.protobuf.FileOpti"
  "ons\030\235\354\003 \001(\010:4\n\014gostring_all\022\034.google.pro"
  "tobuf.FileOptions\030\236\354\003 \001(\010:4\n\014populate_al"
  "l\022\034.google.protobuf.FileOptions\030\237\354\003 \001(\010:"
  "4\n\014stringer_all\022\034.google.protobuf.FileOp"
  "tions\030\240\354\003 \001(\010:3\n\013onlyone_all\022\034.google.pr"
  "otobuf.FileOptions\030\241\354\003 \001(\010:1\n\tequal_all\022"
  "\034.google.protobuf.FileOptions\030\245\354\003 \001(\010:7\n"
  "\017description_all\022\034.google.protobuf.FileO"
  "ptions\030\246\354\003 \001(\010:3\n\013testgen_all\022\034.google.p"
  "rotobuf.FileOptions\030\247\354\003 \001(\010:4\n\014benchgen_"
  "all\022\034.google.protobuf.FileOptions\030\250\354\003 \001("
  "\010:5\n\rmarshaler_all\022\034.google.protobuf.Fil"
  "eOptions\030\251\354\003 \001(\010:7\n\017unmarshaler_all\022\034.go"
  "ogle.protobuf.FileOptions\030\252\354\003 \001(\010:<\n\024sta"
  "ble_marshaler_all\022\034.google.protobuf.File"
  "Options\030\253\354\003 \001(\010:1\n\tsizer_all\022\034.google.pr"
  "otobuf.FileOptions\030\254\354\003 \001(\010:A\n\031goproto_en"
  "um_stringer_all\022\034.google.protobuf.FileOp"
  "tions\030\255\354\003 \001(\010:9\n\021enum_stringer_all\022\034.goo"
  "gle.protobuf.FileOptions\030\256\354\003 \001(\010:<\n\024unsa"
  "fe_marshaler_all\022\034.google.protobuf.FileO"
  "ptions\030\257\354\003 \001(\010:>\n\026unsafe_unmarshaler_all"
  "\022\034.google.protobuf.FileOptions\030\260\354\003 \001(\010:B"
  "\n\032goproto_extensions_map_all\022\034.google.pr"
  "otobuf.FileOptions\030\261\354\003 \001(\010:@\n\030goproto_un"
  "recognized_all\022\034.google.protobuf.FileOpt"
  "ions\030\262\354\003 \001(\010:8\n\020gogoproto_import\022\034.googl"
  "e.protobuf.FileOptions\030\263\354\003 \001(\010:6\n\016protos"
  "izer_all\022\034.google.protobuf.FileOptions\030\264"
  "\354\003 \001(\010:3\n\013compare_all\022\034.google.protobuf."
  "FileOptions\030\265\354\003 \001(\010:4\n\014typedecl_all\022\034.go"
  "ogle.protobuf.FileOptions\030\266\354\003 \001(\010:4\n\014enu"
  "mdecl_all\022\034.google.protobuf.FileOptions\030"
  "\267\354\003 \001(\010:<\n\024goproto_registration\022\034.google"
  ".protobuf.FileOptions\030\270\354\003 \001(\010:7\n\017message"
  "name_all\022\034.google.protobuf.FileOptions\030\271"
  "\354\003 \001(\010:=\n\025goproto_sizecache_all\022\034.google"
  ".protobuf.FileOptions\030\272\354\003 \001(\010:;\n\023goproto"
  "_unkeyed_all\022\034.google.protobuf.FileOptio"
  "ns\030\273\354\003 \001(\010::\n\017goproto_getters\022\037.google.p"
  "rotobuf.MessageOptions\030\201\364\003 \001(\010:;\n\020goprot"
  "o_stringer\022\037.google.protobuf.MessageOpti"
  "ons\030\203\364\003 \001(\010:8\n\rverbose_equal\022\037.google.pr"
  "otobuf.MessageOptions\030\204\364\003 \001(\010:/\n\004face\022\037."
  "google.protobuf.MessageOptions\030\205\364\003 \001(\010:3"
  "\n\010gostring\022\037.google.protobuf.MessageOpti"
  "ons\030\206\364\003 \001(\010:3\n\010populate\022\037.google.protobu"
  "f.MessageOptions\030\207\364\003 \001(\010:3\n\010stringer\022\037.g"
  "oogle.protobuf.MessageOptions\030\300\213\004 \001(\010:2\n"
  "\007onlyone\022\037.google.protobuf.MessageOption"
  "s\030\211\364\003 \001(\010:0\n\005equal\022\037.google.protobuf.Mes"
  "sageOptions\030\215\364\003 \001(\010:6\n\013description\022\037.goo"
  "gle.protobuf.MessageOptions\030\216\364\003 \001(\010:2\n\007t"
  "estgen\022\037.google.protobuf.MessageOptions\030"
  "\217\364\003 \001(\010:3\n\010benchgen\022\037.google.protobuf.Me"
  "ssageOptions\030\220\364\003 \001(\010:4\n\tmarshaler\022\037.goog"
  "le.protobuf.MessageOptions\030\221\364\003 \001(\010:6\n\013un"
  "marshaler\022\037.google.protobuf.MessageOptio"
  "ns\030\222\364\003 \001(\010:;\n\020stable_marshaler\022\037.google."
  "protobuf.MessageOptions\030\223\364\003 \001(\010:0\n\005sizer"
  "\022\037.google.protobuf.MessageOptions\030\224\364\003 \001("
  "\010:;\n\020unsafe_marshaler\022\037.google.protobuf."
  "MessageOptions\030\227\364\003 \001(\010:=\n\022unsafe_unmarsh"
  "aler\022\037.google.protobuf.MessageOptions\030\230\364"
  "\003 \001(\010:A\n\026goproto_extensions_map\022\037.google"
  ".protobuf.MessageOptions\030\231\364\003 \001(\010:\?\n\024gopr"
  "oto_unrecognized\022\037.google.protobuf.Messa"
  "geOptions\030\232\364\003 \001(\010:5\n\nprotosizer\022\037.google"
  ".protobuf.MessageOptions\030\234\364\003 \001(\010:2\n\007comp"
  "are\022\037.google.protobuf.MessageOptions\030\235\364\003"
  " \001(\010:3\n\010typedecl\022\037.google.protobuf.Messa"
  "geOptions\030\236\364\003 \001(\010:6\n\013messagename\022\037.googl"
  "e.protobuf.MessageOptions\030\241\364\003 \001(\010:<\n\021gop"
  "roto_sizecache\022\037.google.protobuf.Message"
  "Options\030\242\364\003 \001(\010::\n\017goproto_unkeyed\022\037.goo"
  "gle.protobuf.MessageOptions\030\243\364\003 \001(\010:1\n\010n"
  "ullable\022\035.google.protobuf.FieldOptions\030\351"
  "\373\003 \001(\010:.\n\005embed\022\035.google.protobuf.FieldO"
  "ptions\030\352\373\003 \001(\010:3\n\ncustomtype\022\035.google.pr"
  "otobuf.FieldOptions\030\353\373\003 \001(\t:3\n\ncustomnam"
  "e\022\035.google.protobuf.FieldOptions\030\354\373\003 \001(\t"
  ":0\n\007jsontag\022\035.google.protobuf.FieldOptio"
  "ns\030\355\373\003 \001(\t:1\n\010moretags\022\035.google.protobuf"
  ".FieldOptions\030\356\373\003 \001(\t:1\n\010casttype\022\035.goog"
  "le.protobuf.FieldOptions\030\357\373\003 \001(\t:0\n\007cast"
  "key\022\035.google.protobuf.FieldOptions\030\360\373\003 \001"
  "(\t:2\n\tcastvalue\022\035.google.protobuf.FieldO"
  "ptions\030\361\373\003 \001(\t:0\n\007stdtime\022\035.google.proto"
  "buf.FieldOptions\030\362\373\003 \001(\010:4\n\013stdduration\022"
  "\035.google.protobuf.FieldOptions\030\363\373\003 \001(\010:3"
  "\n\nwktpointer\022\035.google.protobuf.FieldOpti"
  "ons\030\364\373\003 \001(\010BE\n\023com.google.protobufB\nGoGo"
  "ProtosZ\"github.com/gogo/protobuf/gogopro"
  "to"
  ;
::google::protobuf::internal::DescriptorTable descriptor_table_gogo_2eproto = {
  false, InitDefaults_gogo_2eproto, 
  descriptor_table_protodef_gogo_2eproto,
  "gogo.proto", &assign_descriptors_table_gogo_2eproto, 4402,
};

void AddDescriptors_gogo_2eproto() {
  static constexpr ::google::protobuf::internal::InitFunc deps[1] =
  {
    ::AddDescriptors_descriptor_2eproto,
  };
 ::google::protobuf::internal::AddDescriptors(&descriptor_table_gogo_2eproto, deps, 1);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_gogo_2eproto = []() { AddDescriptors_gogo_2eproto(); return true; }();
namespace gogoproto {
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::EnumOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  goproto_enum_prefix(kGoprotoEnumPrefixFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::EnumOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  goproto_enum_stringer(kGoprotoEnumStringerFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::EnumOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  enum_stringer(kEnumStringerFieldNumber, false);
const ::std::string enum_customname_default("");
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::EnumOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  enum_customname(kEnumCustomnameFieldNumber, enum_customname_default);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::EnumOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  enumdecl(kEnumdeclFieldNumber, false);
const ::std::string enumvalue_customname_default("");
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::EnumValueOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  enumvalue_customname(kEnumvalueCustomnameFieldNumber, enumvalue_customname_default);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  goproto_getters_all(kGoprotoGettersAllFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  goproto_enum_prefix_all(kGoprotoEnumPrefixAllFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  goproto_stringer_all(kGoprotoStringerAllFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  verbose_equal_all(kVerboseEqualAllFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  face_all(kFaceAllFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  gostring_all(kGostringAllFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  populate_all(kPopulateAllFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  stringer_all(kStringerAllFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  onlyone_all(kOnlyoneAllFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  equal_all(kEqualAllFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  description_all(kDescriptionAllFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  testgen_all(kTestgenAllFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  benchgen_all(kBenchgenAllFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  marshaler_all(kMarshalerAllFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  unmarshaler_all(kUnmarshalerAllFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  stable_marshaler_all(kStableMarshalerAllFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  sizer_all(kSizerAllFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  goproto_enum_stringer_all(kGoprotoEnumStringerAllFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  enum_stringer_all(kEnumStringerAllFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  unsafe_marshaler_all(kUnsafeMarshalerAllFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  unsafe_unmarshaler_all(kUnsafeUnmarshalerAllFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  goproto_extensions_map_all(kGoprotoExtensionsMapAllFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  goproto_unrecognized_all(kGoprotoUnrecognizedAllFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  gogoproto_import(kGogoprotoImportFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  protosizer_all(kProtosizerAllFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  compare_all(kCompareAllFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  typedecl_all(kTypedeclAllFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  enumdecl_all(kEnumdeclAllFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  goproto_registration(kGoprotoRegistrationFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  messagename_all(kMessagenameAllFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  goproto_sizecache_all(kGoprotoSizecacheAllFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  goproto_unkeyed_all(kGoprotoUnkeyedAllFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  goproto_getters(kGoprotoGettersFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  goproto_stringer(kGoprotoStringerFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  verbose_equal(kVerboseEqualFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  face(kFaceFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  gostring(kGostringFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  populate(kPopulateFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  stringer(kStringerFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  onlyone(kOnlyoneFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  equal(kEqualFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  description(kDescriptionFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  testgen(kTestgenFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  benchgen(kBenchgenFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  marshaler(kMarshalerFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  unmarshaler(kUnmarshalerFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  stable_marshaler(kStableMarshalerFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  sizer(kSizerFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  unsafe_marshaler(kUnsafeMarshalerFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  unsafe_unmarshaler(kUnsafeUnmarshalerFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  goproto_extensions_map(kGoprotoExtensionsMapFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  goproto_unrecognized(kGoprotoUnrecognizedFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  protosizer(kProtosizerFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  compare(kCompareFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  typedecl(kTypedeclFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  messagename(kMessagenameFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  goproto_sizecache(kGoprotoSizecacheFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  goproto_unkeyed(kGoprotoUnkeyedFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  nullable(kNullableFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  embed(kEmbedFieldNumber, false);
const ::std::string customtype_default("");
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  customtype(kCustomtypeFieldNumber, customtype_default);
const ::std::string customname_default("");
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  customname(kCustomnameFieldNumber, customname_default);
const ::std::string jsontag_default("");
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  jsontag(kJsontagFieldNumber, jsontag_default);
const ::std::string moretags_default("");
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  moretags(kMoretagsFieldNumber, moretags_default);
const ::std::string casttype_default("");
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  casttype(kCasttypeFieldNumber, casttype_default);
const ::std::string castkey_default("");
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  castkey(kCastkeyFieldNumber, castkey_default);
const ::std::string castvalue_default("");
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  castvalue(kCastvalueFieldNumber, castvalue_default);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  stdtime(kStdtimeFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  stdduration(kStddurationFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  wktpointer(kWktpointerFieldNumber, false);

// @@protoc_insertion_point(namespace_scope)
}  // namespace gogoproto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
